INSERT INTO public.ingredients (slug, name, aliases, category, vegan, vegetarian, source, explanation, e_number, confidence, verification)
VALUES
('peach','Peach',ARRAY['peaches']::text[],'plant',true,true,NULL,'Peach is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('pear','Pear',ARRAY['pears']::text[],'plant',true,true,NULL,'Pear is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('plum','Plum',ARRAY['plums']::text[],'plant',true,true,NULL,'Plum is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('apricot','Apricot',ARRAY['apricots']::text[],'plant',true,true,NULL,'Apricot is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('cherry','Cherry',ARRAY['cherries']::text[],'plant',true,true,NULL,'Cherry is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('watermelon','Watermelon','{}'::text[],'plant',true,true,NULL,'Watermelon is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('cantaloupe','Cantaloupe',ARRAY['muskmelon']::text[],'plant',true,true,NULL,'Cantaloupe is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('honeydew','Honeydew Melon',ARRAY['honeydew-melon']::text[],'plant',true,true,NULL,'Honeydew Melon is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('pineapple','Pineapple','{}'::text[],'plant',true,true,NULL,'Pineapple is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('papaya','Papaya','{}'::text[],'plant',true,true,NULL,'Papaya is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('guava','Guava','{}'::text[],'plant',true,true,NULL,'Guava is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('kiwi','Kiwi',ARRAY['kiwifruit']::text[],'plant',true,true,NULL,'Kiwi is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('pomegranate','Pomegranate','{}'::text[],'plant',true,true,NULL,'Pomegranate is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('fig','Fig',ARRAY['figs']::text[],'plant',true,true,NULL,'Fig is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('raspberry','Raspberry',ARRAY['raspberries']::text[],'plant',true,true,NULL,'Raspberry is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('blackberry','Blackberry',ARRAY['blackberries']::text[],'plant',true,true,NULL,'Blackberry is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('strawberry','Strawberry',ARRAY['strawberries']::text[],'plant',true,true,NULL,'Strawberry is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('currant','Currant',ARRAY['currants','black currant','red currant']::text[],'plant',true,true,NULL,'Currant is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('gooseberry','Gooseberry','{}'::text[],'plant',true,true,NULL,'Gooseberry is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('persimmon','Persimmon','{}'::text[],'plant',true,true,NULL,'Persimmon is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('lychee','Lychee',ARRAY['litchi']::text[],'plant',true,true,NULL,'Lychee is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('passion-fruit','Passion Fruit',ARRAY['passionfruit']::text[],'plant',true,true,NULL,'Passion Fruit is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('dragon-fruit','Dragon Fruit',ARRAY['pitaya']::text[],'plant',true,true,NULL,'Dragon Fruit is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('jackfruit','Jackfruit','{}'::text[],'plant',true,true,NULL,'Jackfruit is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('tangerine','Tangerine','{}'::text[],'plant',true,true,NULL,'Tangerine is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('mandarin','Mandarin Orange',ARRAY['mandarin']::text[],'plant',true,true,NULL,'Mandarin Orange is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('orange','Orange',ARRAY['oranges']::text[],'plant',true,true,NULL,'Orange is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('grapefruit','Grapefruit','{}'::text[],'plant',true,true,NULL,'Grapefruit is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('clementine','Clementine','{}'::text[],'plant',true,true,NULL,'Clementine is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('elderberry','Elderberry','{}'::text[],'plant',true,true,NULL,'Elderberry is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('acai','Acai',ARRAY['açaí','acai berry']::text[],'plant',true,true,NULL,'Acai is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('goji-berry','Goji Berry',ARRAY['goji']::text[],'plant',true,true,NULL,'Goji Berry is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('mulberry','Mulberry','{}'::text[],'plant',true,true,NULL,'Mulberry is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('quince','Quince','{}'::text[],'plant',true,true,NULL,'Quince is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('rhubarb','Rhubarb','{}'::text[],'plant',true,true,NULL,'Rhubarb is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('nectarine','Nectarine','{}'::text[],'plant',true,true,NULL,'Nectarine is a whole plant food; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('asparagus','Asparagus','{}'::text[],'plant',true,true,NULL,'Asparagus is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('brussels-sprout','Brussels Sprouts',ARRAY['brussels sprout']::text[],'plant',true,true,NULL,'Brussels Sprouts is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('artichoke','Artichoke','{}'::text[],'plant',true,true,NULL,'Artichoke is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('eggplant','Eggplant',ARRAY['aubergine']::text[],'plant',true,true,NULL,'Eggplant is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('zucchini','Zucchini',ARRAY['courgette']::text[],'plant',true,true,NULL,'Zucchini is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('cucumber','Cucumber','{}'::text[],'plant',true,true,NULL,'Cucumber is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('spinach','Spinach','{}'::text[],'plant',true,true,NULL,'Spinach is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('arugula','Arugula',ARRAY['rocket']::text[],'plant',true,true,NULL,'Arugula is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('swiss-chard','Swiss Chard',ARRAY['chard']::text[],'plant',true,true,NULL,'Swiss Chard is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('collard-greens','Collard Greens',ARRAY['collards']::text[],'plant',true,true,NULL,'Collard Greens is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('bok-choy','Bok Choy',ARRAY['pak choi']::text[],'plant',true,true,NULL,'Bok Choy is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('endive','Endive','{}'::text[],'plant',true,true,NULL,'Endive is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('watercress','Watercress','{}'::text[],'plant',true,true,NULL,'Watercress is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('fennel','Fennel','{}'::text[],'plant',true,true,NULL,'Fennel is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('leek','Leek',ARRAY['leeks']::text[],'plant',true,true,NULL,'Leek is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('shallot','Shallot',ARRAY['shallots']::text[],'plant',true,true,NULL,'Shallot is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('scallion','Scallion',ARRAY['green onion','spring onion']::text[],'plant',true,true,NULL,'Scallion is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('turnip','Turnip','{}'::text[],'plant',true,true,NULL,'Turnip is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('rutabaga','Rutabaga',ARRAY['swede']::text[],'plant',true,true,NULL,'Rutabaga is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('parsnip','Parsnip','{}'::text[],'plant',true,true,NULL,'Parsnip is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('radish','Radish','{}'::text[],'plant',true,true,NULL,'Radish is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('daikon','Daikon','{}'::text[],'plant',true,true,NULL,'Daikon is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('okra','Okra',ARRAY['ladyfinger']::text[],'plant',true,true,NULL,'Okra is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('sweet-potato','Sweet Potato','{}'::text[],'plant',true,true,NULL,'Sweet Potato is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('yam','Yam','{}'::text[],'plant',true,true,NULL,'Yam is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('taro','Taro','{}'::text[],'plant',true,true,NULL,'Taro is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('cassava','Cassava',ARRAY['manioc','yuca']::text[],'plant',true,true,NULL,'Cassava is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('plantain','Plantain','{}'::text[],'plant',true,true,NULL,'Plantain is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('pumpkin','Pumpkin','{}'::text[],'plant',true,true,NULL,'Pumpkin is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('butternut-squash','Butternut Squash','{}'::text[],'plant',true,true,NULL,'Butternut Squash is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('acorn-squash','Acorn Squash','{}'::text[],'plant',true,true,NULL,'Acorn Squash is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('spaghetti-squash','Spaghetti Squash','{}'::text[],'plant',true,true,NULL,'Spaghetti Squash is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('green-bean','Green Bean',ARRAY['green beans','string bean']::text[],'plant',true,true,NULL,'Green Bean is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('snow-pea','Snow Pea',ARRAY['snow peas']::text[],'plant',true,true,NULL,'Snow Pea is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('snap-pea','Snap Pea',ARRAY['sugar snap pea']::text[],'plant',true,true,NULL,'Snap Pea is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('potato','Potato',ARRAY['potatoes']::text[],'plant',true,true,NULL,'Potato is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('onion','Onion',ARRAY['onions']::text[],'plant',true,true,NULL,'Onion is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('tomato','Tomato',ARRAY['tomatoes']::text[],'plant',true,true,NULL,'Tomato is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('avocado','Avocado','{}'::text[],'plant',true,true,NULL,'Avocado is a vegetable; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('navy-bean','Navy Bean','{}'::text[],'plant',true,true,NULL,'Navy Bean is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('pinto-bean','Pinto Bean','{}'::text[],'plant',true,true,NULL,'Pinto Bean is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('black-eyed-pea','Black-Eyed Pea',ARRAY['black-eyed peas']::text[],'plant',true,true,NULL,'Black-Eyed Pea is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('mung-bean','Mung Bean','{}'::text[],'plant',true,true,NULL,'Mung Bean is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('adzuki-bean','Adzuki Bean',ARRAY['aduki bean']::text[],'plant',true,true,NULL,'Adzuki Bean is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('fava-bean','Fava Bean',ARRAY['broad bean']::text[],'plant',true,true,NULL,'Fava Bean is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('lima-bean','Lima Bean',ARRAY['butter bean']::text[],'plant',true,true,NULL,'Lima Bean is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('edamame','Edamame','{}'::text[],'plant',true,true,NULL,'Edamame is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('soybean','Soybean',ARRAY['soya bean']::text[],'plant',true,true,NULL,'Soybean is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('tofu','Tofu','{}'::text[],'plant',true,true,NULL,'Tofu is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('tempeh','Tempeh','{}'::text[],'plant',true,true,NULL,'Tempeh is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('seitan','Seitan',ARRAY['wheat meat']::text[],'plant',true,true,NULL,'Seitan is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('textured-vegetable-protein','Textured Vegetable Protein',ARRAY['tvp','textured soy protein']::text[],'plant',true,true,NULL,'Textured Vegetable Protein is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('soy-milk','Soy Milk',ARRAY['soya milk']::text[],'plant',true,true,NULL,'Soy Milk is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('oat-milk','Oat Milk','{}'::text[],'plant',true,true,NULL,'Oat Milk is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('rice-milk','Rice Milk','{}'::text[],'plant',true,true,NULL,'Rice Milk is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('hemp-milk','Hemp Milk','{}'::text[],'plant',true,true,NULL,'Hemp Milk is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('cashew-milk','Cashew Milk','{}'::text[],'plant',true,true,NULL,'Cashew Milk is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('pea-protein','Pea Protein',ARRAY['pea protein isolate']::text[],'plant',true,true,NULL,'Pea Protein is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('soy-protein','Soy Protein',ARRAY['soy protein isolate','soya protein']::text[],'plant',true,true,NULL,'Soy Protein is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('wheat-gluten','Wheat Gluten',ARRAY['vital wheat gluten']::text[],'plant',true,true,NULL,'Wheat Gluten is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('chickpea-flour','Chickpea Flour',ARRAY['gram flour','besan']::text[],'plant',true,true,NULL,'Chickpea Flour is a plant-based protein or milk; vegan and vegetarian.',NULL,0.95,'verified'),
('quinoa','Quinoa','{}'::text[],'plant',true,true,NULL,'Quinoa is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('millet','Millet','{}'::text[],'plant',true,true,NULL,'Millet is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('sorghum','Sorghum','{}'::text[],'plant',true,true,NULL,'Sorghum is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('buckwheat','Buckwheat','{}'::text[],'plant',true,true,NULL,'Buckwheat is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('spelt','Spelt','{}'::text[],'plant',true,true,NULL,'Spelt is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('farro','Farro','{}'::text[],'plant',true,true,NULL,'Farro is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('teff','Teff','{}'::text[],'plant',true,true,NULL,'Teff is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('bulgur','Bulgur','{}'::text[],'plant',true,true,NULL,'Bulgur is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('couscous','Couscous','{}'::text[],'plant',true,true,NULL,'Couscous is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('semolina','Semolina','{}'::text[],'plant',true,true,NULL,'Semolina is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('rye','Rye','{}'::text[],'plant',true,true,NULL,'Rye is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('wild-rice','Wild Rice','{}'::text[],'plant',true,true,NULL,'Wild Rice is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('brown-rice','Brown Rice','{}'::text[],'plant',true,true,NULL,'Brown Rice is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('white-rice','White Rice','{}'::text[],'plant',true,true,NULL,'White Rice is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('jasmine-rice','Jasmine Rice','{}'::text[],'plant',true,true,NULL,'Jasmine Rice is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('basmati-rice','Basmati Rice','{}'::text[],'plant',true,true,NULL,'Basmati Rice is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('oats','Oats',ARRAY['oat']::text[],'plant',true,true,NULL,'Oats is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('rolled-oats','Rolled Oats','{}'::text[],'plant',true,true,NULL,'Rolled Oats is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('oat-flour','Oat Flour','{}'::text[],'plant',true,true,NULL,'Oat Flour is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('whole-wheat-flour','Whole Wheat Flour',ARRAY['wholemeal flour']::text[],'plant',true,true,NULL,'Whole Wheat Flour is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('all-purpose-flour','All-Purpose Flour',ARRAY['plain flour']::text[],'plant',true,true,NULL,'All-Purpose Flour is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('rice-flour','Rice Flour','{}'::text[],'plant',true,true,NULL,'Rice Flour is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('tapioca-flour','Tapioca Flour',ARRAY['tapioca starch']::text[],'plant',true,true,NULL,'Tapioca Flour is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('potato-starch','Potato Starch','{}'::text[],'plant',true,true,NULL,'Potato Starch is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('arrowroot','Arrowroot',ARRAY['arrowroot starch']::text[],'plant',true,true,NULL,'Arrowroot is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('bran','Bran',ARRAY['wheat bran']::text[],'plant',true,true,NULL,'Bran is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('wheat-germ','Wheat Germ','{}'::text[],'plant',true,true,NULL,'Wheat Germ is a grain product; naturally vegan and vegetarian.',NULL,0.95,'verified'),
('peanut','Peanut',ARRAY['peanuts','groundnut']::text[],'plant',true,true,NULL,'Peanut comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('pistachio','Pistachio',ARRAY['pistachios']::text[],'plant',true,true,NULL,'Pistachio comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('walnut','Walnut',ARRAY['walnuts']::text[],'plant',true,true,NULL,'Walnut comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('pecan','Pecan',ARRAY['pecans']::text[],'plant',true,true,NULL,'Pecan comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('brazil-nut','Brazil Nut','{}'::text[],'plant',true,true,NULL,'Brazil Nut comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('macadamia','Macadamia',ARRAY['macadamia nut']::text[],'plant',true,true,NULL,'Macadamia comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('pine-nut','Pine Nut',ARRAY['pignoli']::text[],'plant',true,true,NULL,'Pine Nut comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('chestnut','Chestnut','{}'::text[],'plant',true,true,NULL,'Chestnut comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('sesame-seed','Sesame Seed',ARRAY['sesame seeds']::text[],'plant',true,true,NULL,'Sesame Seed comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('sunflower-seed','Sunflower Seed','{}'::text[],'plant',true,true,NULL,'Sunflower Seed comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('pumpkin-seed','Pumpkin Seed',ARRAY['pepita']::text[],'plant',true,true,NULL,'Pumpkin Seed comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('chia-seed','Chia Seed',ARRAY['chia seeds']::text[],'plant',true,true,NULL,'Chia Seed comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('flaxseed','Flaxseed',ARRAY['linseed','flax seed']::text[],'plant',true,true,NULL,'Flaxseed comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('hemp-seed','Hemp Seed',ARRAY['hemp hearts']::text[],'plant',true,true,NULL,'Hemp Seed comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('poppy-seed','Poppy Seed','{}'::text[],'plant',true,true,NULL,'Poppy Seed comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('tahini','Tahini',ARRAY['sesame paste']::text[],'plant',true,true,NULL,'Tahini comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('peanut-butter','Peanut Butter','{}'::text[],'plant',true,true,NULL,'Peanut Butter comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('almond-butter','Almond Butter','{}'::text[],'plant',true,true,NULL,'Almond Butter comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('cashew-butter','Cashew Butter','{}'::text[],'plant',true,true,NULL,'Cashew Butter comes from plants; vegan and vegetarian.',NULL,0.95,'verified'),
('rosemary','Rosemary','{}'::text[],'plant',true,true,NULL,'Rosemary is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('thyme','Thyme','{}'::text[],'plant',true,true,NULL,'Thyme is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('oregano','Oregano','{}'::text[],'plant',true,true,NULL,'Oregano is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('sage','Sage','{}'::text[],'plant',true,true,NULL,'Sage is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('mint','Mint',ARRAY['peppermint','spearmint']::text[],'plant',true,true,NULL,'Mint is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('parsley','Parsley','{}'::text[],'plant',true,true,NULL,'Parsley is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('dill','Dill','{}'::text[],'plant',true,true,NULL,'Dill is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('chive','Chive',ARRAY['chives']::text[],'plant',true,true,NULL,'Chive is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('bay-leaf','Bay Leaf',ARRAY['bay leaves']::text[],'plant',true,true,NULL,'Bay Leaf is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('tarragon','Tarragon','{}'::text[],'plant',true,true,NULL,'Tarragon is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('marjoram','Marjoram','{}'::text[],'plant',true,true,NULL,'Marjoram is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('nutmeg','Nutmeg','{}'::text[],'plant',true,true,NULL,'Nutmeg is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('allspice','Allspice','{}'::text[],'plant',true,true,NULL,'Allspice is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('cardamom','Cardamom','{}'::text[],'plant',true,true,NULL,'Cardamom is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('star-anise','Star Anise','{}'::text[],'plant',true,true,NULL,'Star Anise is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('anise','Anise',ARRAY['aniseed']::text[],'plant',true,true,NULL,'Anise is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('saffron','Saffron','{}'::text[],'plant',true,true,NULL,'Saffron is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('paprika','Paprika',ARRAY['smoked paprika']::text[],'plant',true,true,NULL,'Paprika is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('cayenne','Cayenne Pepper',ARRAY['cayenne']::text[],'plant',true,true,NULL,'Cayenne Pepper is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('chili-powder','Chili Powder',ARRAY['chilli powder']::text[],'plant',true,true,NULL,'Chili Powder is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('turmeric','Turmeric','{}'::text[],'plant',true,true,NULL,'Turmeric is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('fenugreek','Fenugreek','{}'::text[],'plant',true,true,NULL,'Fenugreek is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('mustard-seed','Mustard Seed',ARRAY['mustard seeds']::text[],'plant',true,true,NULL,'Mustard Seed is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('caraway','Caraway',ARRAY['caraway seed']::text[],'plant',true,true,NULL,'Caraway is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('sumac','Sumac','{}'::text[],'plant',true,true,NULL,'Sumac is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('vanilla','Vanilla','{}'::text[],'plant',true,true,NULL,'Vanilla is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('vanilla-extract','Vanilla Extract','{}'::text[],'plant',true,true,NULL,'Vanilla Extract is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('cocoa-powder','Cocoa Powder','{}'::text[],'plant',true,true,NULL,'Cocoa Powder is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('white-pepper','White Pepper','{}'::text[],'plant',true,true,NULL,'White Pepper is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('curry-powder','Curry Powder','{}'::text[],'plant',true,true,NULL,'Curry Powder is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('garam-masala','Garam Masala','{}'::text[],'plant',true,true,NULL,'Garam Masala is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('herbes-de-provence','Herbes de Provence','{}'::text[],'plant',true,true,NULL,'Herbes de Provence is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('italian-seasoning','Italian Seasoning','{}'::text[],'plant',true,true,NULL,'Italian Seasoning is a plant-derived herb, spice, or seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('salt','Salt',ARRAY['table salt','sodium chloride']::text[],'mineral',true,true,NULL,'Salt is a mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('sea-salt','Sea Salt','{}'::text[],'mineral',true,true,NULL,'Sea Salt is a mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('himalayan-salt','Himalayan Pink Salt',ARRAY['pink salt']::text[],'mineral',true,true,NULL,'Himalayan Pink Salt is a mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('olive-oil','Olive Oil',ARRAY['extra virgin olive oil','evoo']::text[],'plant',true,true,NULL,'Olive Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('sunflower-oil','Sunflower Oil','{}'::text[],'plant',true,true,NULL,'Sunflower Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('safflower-oil','Safflower Oil','{}'::text[],'plant',true,true,NULL,'Safflower Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('peanut-oil','Peanut Oil',ARRAY['groundnut oil']::text[],'plant',true,true,NULL,'Peanut Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('sesame-oil','Sesame Oil','{}'::text[],'plant',true,true,NULL,'Sesame Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('avocado-oil','Avocado Oil','{}'::text[],'plant',true,true,NULL,'Avocado Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('grapeseed-oil','Grapeseed Oil','{}'::text[],'plant',true,true,NULL,'Grapeseed Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('rice-bran-oil','Rice Bran Oil','{}'::text[],'plant',true,true,NULL,'Rice Bran Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('palm-oil','Palm Oil','{}'::text[],'plant',true,true,NULL,'Palm Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('palm-kernel-oil','Palm Kernel Oil','{}'::text[],'plant',true,true,NULL,'Palm Kernel Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('cottonseed-oil','Cottonseed Oil','{}'::text[],'plant',true,true,NULL,'Cottonseed Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('corn-oil','Corn Oil','{}'::text[],'plant',true,true,NULL,'Corn Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('soybean-oil','Soybean Oil',ARRAY['soya oil']::text[],'plant',true,true,NULL,'Soybean Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('flaxseed-oil','Flaxseed Oil',ARRAY['linseed oil']::text[],'plant',true,true,NULL,'Flaxseed Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('walnut-oil','Walnut Oil','{}'::text[],'plant',true,true,NULL,'Walnut Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('mct-oil','MCT Oil',ARRAY['medium chain triglycerides']::text[],'plant',true,true,NULL,'MCT Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('hydrogenated-vegetable-oil','Hydrogenated Vegetable Oil','{}'::text[],'plant',true,true,NULL,'Hydrogenated Vegetable Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('vegetable-shortening','Vegetable Shortening','{}'::text[],'plant',true,true,NULL,'Vegetable Shortening is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('vegetable-oil','Vegetable Oil','{}'::text[],'plant',true,true,NULL,'Vegetable Oil is a plant-derived oil or fat; vegan and vegetarian.',NULL,0.95,'verified'),
('margarine','Margarine',ARRAY['margarine spread']::text[],'unknown',NULL,NULL,NULL,'Margarine is usually plant-based but many brands add milk solids, whey, or vitamin D3 from lanolin. Check the label.',NULL,0.6,'verified'),
('maple-syrup','Maple Syrup','{}'::text[],'plant',true,true,NULL,'Maple Syrup is a plant-derived sweetener; vegan and vegetarian.',NULL,0.95,'verified'),
('brown-rice-syrup','Brown Rice Syrup','{}'::text[],'plant',true,true,NULL,'Brown Rice Syrup is a plant-derived sweetener; vegan and vegetarian.',NULL,0.95,'verified'),
('molasses','Molasses','{}'::text[],'plant',true,true,NULL,'Molasses is a plant-derived sweetener; vegan and vegetarian.',NULL,0.95,'verified'),
('sorghum-syrup','Sorghum Syrup','{}'::text[],'plant',true,true,NULL,'Sorghum Syrup is a plant-derived sweetener; vegan and vegetarian.',NULL,0.95,'verified'),
('date-syrup','Date Syrup','{}'::text[],'plant',true,true,NULL,'Date Syrup is a plant-derived sweetener; vegan and vegetarian.',NULL,0.95,'verified'),
('monk-fruit-extract','Monk Fruit Extract',ARRAY['luo han guo']::text[],'plant',true,true,NULL,'Monk Fruit Extract is a plant-derived sweetener; vegan and vegetarian.',NULL,0.95,'verified'),
('stevia','Stevia',ARRAY['steviol glycosides']::text[],'plant',true,true,NULL,'Stevia is a plant-derived sweetener; vegan and vegetarian.','E960',0.95,'verified'),
('sucralose','Sucralose','{}'::text[],'synthetic',true,true,NULL,'Sucralose is a synthetic sweetener; vegan and vegetarian.','E955',0.95,'verified'),
('saccharin','Saccharin','{}'::text[],'synthetic',true,true,NULL,'Saccharin is a synthetic sweetener; vegan and vegetarian.','E954',0.95,'verified'),
('xylitol','Xylitol','{}'::text[],'synthetic',true,true,NULL,'Xylitol is a sugar alcohol; vegan and vegetarian.','E967',0.95,'verified'),
('sorbitol','Sorbitol','{}'::text[],'synthetic',true,true,NULL,'Sorbitol is a sugar alcohol; vegan and vegetarian.','E420',0.95,'verified'),
('isomalt','Isomalt','{}'::text[],'synthetic',true,true,NULL,'Isomalt is a sugar alcohol; vegan and vegetarian.','E953',0.95,'verified'),
('lactitol','Lactitol','{}'::text[],'unknown',NULL,NULL,NULL,'Lactitol is a sugar alcohol derived from lactose (dairy). Not vegan; typically vegetarian.','E966',0.6,'verified'),
('maltitol','Maltitol','{}'::text[],'synthetic',true,true,NULL,'Maltitol is a sugar alcohol; vegan and vegetarian.','E965',0.95,'verified'),
('neotame','Neotame','{}'::text[],'synthetic',true,true,NULL,'Neotame is a synthetic sweetener; vegan and vegetarian.','E961',0.95,'verified'),
('cyclamate','Cyclamate','{}'::text[],'synthetic',true,true,NULL,'Cyclamate is a synthetic sweetener; vegan and vegetarian.','E952',0.95,'verified'),
('thaumatin','Thaumatin','{}'::text[],'plant',true,true,NULL,'Thaumatin is a plant-derived sweet protein; vegan and vegetarian.','E957',0.95,'verified'),
('polydextrose','Polydextrose','{}'::text[],'synthetic',true,true,NULL,'Polydextrose is a synthetic fiber; vegan and vegetarian.','E1200',0.95,'verified'),
('high-fructose-corn-syrup','High-Fructose Corn Syrup',ARRAY['hfcs']::text[],'plant',true,true,NULL,'HFCS is corn-derived; vegan and vegetarian.',NULL,0.95,'verified'),
('invert-sugar','Invert Sugar','{}'::text[],'plant',true,true,NULL,'Invert sugar from cane or beet; vegan and vegetarian.',NULL,0.95,'verified'),
('turbinado-sugar','Turbinado Sugar','{}'::text[],'plant',true,true,NULL,'Raw cane sugar; vegan and vegetarian.',NULL,0.95,'verified'),
('demerara-sugar','Demerara Sugar','{}'::text[],'plant',true,true,NULL,'Cane sugar; vegan and vegetarian.',NULL,0.95,'verified'),
('muscovado-sugar','Muscovado Sugar','{}'::text[],'plant',true,true,NULL,'Cane sugar; vegan and vegetarian.',NULL,0.95,'verified'),
('powdered-sugar','Powdered Sugar',ARRAY['icing sugar']::text[],'plant',true,true,NULL,'Ground sugar with starch; vegan and vegetarian.',NULL,0.95,'verified'),
('nori','Nori',ARRAY['sushi seaweed']::text[],'plant',true,true,NULL,'Nori is edible seaweed; vegan and vegetarian.',NULL,0.95,'verified'),
('kombu','Kombu','{}'::text[],'plant',true,true,NULL,'Kombu is edible seaweed; vegan and vegetarian.',NULL,0.95,'verified'),
('wakame','Wakame','{}'::text[],'plant',true,true,NULL,'Wakame is edible seaweed; vegan and vegetarian.',NULL,0.95,'verified'),
('dulse','Dulse','{}'::text[],'plant',true,true,NULL,'Dulse is edible seaweed; vegan and vegetarian.',NULL,0.95,'verified'),
('spirulina','Spirulina','{}'::text[],'microbial',true,true,NULL,'Spirulina is a blue-green algae; vegan and vegetarian.',NULL,0.95,'verified'),
('chlorella','Chlorella','{}'::text[],'microbial',true,true,NULL,'Chlorella is a green algae; vegan and vegetarian.',NULL,0.95,'verified'),
('nutritional-yeast','Nutritional Yeast',ARRAY['nooch']::text[],'microbial',true,true,NULL,'Deactivated yeast used as seasoning; vegan and vegetarian.',NULL,0.95,'verified'),
('brewers-yeast','Brewer''s Yeast','{}'::text[],'microbial',true,true,NULL,'Yeast byproduct of brewing; vegan and vegetarian.',NULL,0.95,'verified'),
('yeast-extract','Yeast Extract','{}'::text[],'microbial',true,true,NULL,'Yeast-derived flavoring; vegan and vegetarian.',NULL,0.95,'verified'),
('kombucha','Kombucha','{}'::text[],'microbial',true,true,NULL,'Fermented tea; vegan and vegetarian.',NULL,0.95,'verified'),
('active-dry-yeast','Active Dry Yeast',ARRAY['baker''s yeast']::text[],'microbial',true,true,NULL,'Baker''s yeast; vegan and vegetarian.',NULL,0.95,'verified'),
('mushroom','Mushroom',ARRAY['mushrooms']::text[],'plant',true,true,NULL,'Mushroom is a fungus consumed as food; vegan and vegetarian.',NULL,0.95,'verified'),
('portobello','Portobello Mushroom','{}'::text[],'plant',true,true,NULL,'Mushroom; vegan and vegetarian.',NULL,0.95,'verified'),
('shiitake','Shiitake','{}'::text[],'plant',true,true,NULL,'Mushroom; vegan and vegetarian.',NULL,0.95,'verified'),
('oyster-mushroom','Oyster Mushroom','{}'::text[],'plant',true,true,NULL,'Mushroom; vegan and vegetarian.',NULL,0.95,'verified'),
('cremini','Cremini Mushroom',ARRAY['baby bella']::text[],'plant',true,true,NULL,'Mushroom; vegan and vegetarian.',NULL,0.95,'verified'),
('enoki','Enoki Mushroom','{}'::text[],'plant',true,true,NULL,'Mushroom; vegan and vegetarian.',NULL,0.95,'verified'),
('porcini','Porcini','{}'::text[],'plant',true,true,NULL,'Mushroom; vegan and vegetarian.',NULL,0.95,'verified'),
('truffle','Truffle',ARRAY['truffles']::text[],'plant',true,true,NULL,'Truffle fungus; vegan and vegetarian.',NULL,0.95,'verified'),
('morel','Morel','{}'::text[],'plant',true,true,NULL,'Morel mushroom; vegan and vegetarian.',NULL,0.95,'verified'),
('pork','Pork','{}'::text[],'animal',false,false,NULL,'Pork is meat from pigs; not vegetarian or vegan.',NULL,0.95,'verified'),
('bacon','Bacon','{}'::text[],'animal',false,false,NULL,'Bacon is cured pork; not vegetarian or vegan.',NULL,0.95,'verified'),
('ham','Ham','{}'::text[],'animal',false,false,NULL,'Ham is cured pork; not vegetarian or vegan.',NULL,0.95,'verified'),
('prosciutto','Prosciutto','{}'::text[],'animal',false,false,NULL,'Dry-cured pork; not vegetarian or vegan.',NULL,0.95,'verified'),
('sausage','Sausage','{}'::text[],'animal',false,false,NULL,'Ground meat product; not vegetarian or vegan.',NULL,0.95,'verified'),
('turkey','Turkey','{}'::text[],'animal',false,false,NULL,'Poultry meat; not vegetarian or vegan.',NULL,0.95,'verified'),
('goose','Goose','{}'::text[],'animal',false,false,NULL,'Poultry meat; not vegetarian or vegan.',NULL,0.95,'verified'),
('venison','Venison',ARRAY['deer meat']::text[],'animal',false,false,NULL,'Deer meat; not vegetarian or vegan.',NULL,0.95,'verified'),
('veal','Veal','{}'::text[],'animal',false,false,NULL,'Calf meat; not vegetarian or vegan.',NULL,0.95,'verified'),
('liver','Liver','{}'::text[],'animal',false,false,NULL,'Animal organ meat; not vegetarian or vegan.',NULL,0.95,'verified'),
('foie-gras','Foie Gras','{}'::text[],'animal',false,false,NULL,'Fattened duck/goose liver; not vegetarian or vegan.',NULL,0.95,'verified'),
('pate','Pâté',ARRAY['pate']::text[],'animal',false,false,NULL,'Ground meat spread; not vegetarian or vegan.',NULL,0.95,'verified'),
('pepperoni','Pepperoni','{}'::text[],'animal',false,false,NULL,'Cured pork/beef sausage; not vegetarian or vegan.',NULL,0.95,'verified'),
('salami','Salami','{}'::text[],'animal',false,false,NULL,'Cured sausage; not vegetarian or vegan.',NULL,0.95,'verified'),
('chorizo','Chorizo','{}'::text[],'animal',false,false,NULL,'Cured pork sausage; not vegetarian or vegan.',NULL,0.95,'verified'),
('hot-dog','Hot Dog',ARRAY['frankfurter','wiener']::text[],'animal',false,false,NULL,'Meat sausage; not vegetarian or vegan.',NULL,0.95,'verified'),
('tallow','Tallow',ARRAY['beef tallow']::text[],'animal',false,false,NULL,'Rendered beef fat; not vegetarian or vegan.',NULL,0.95,'verified'),
('suet','Suet','{}'::text[],'animal',false,false,NULL,'Raw animal fat; not vegetarian or vegan.',NULL,0.95,'verified'),
('schmaltz','Schmaltz',ARRAY['chicken fat']::text[],'animal',false,false,NULL,'Rendered chicken/goose fat; not vegetarian or vegan.',NULL,0.95,'verified'),
('ghee','Ghee',ARRAY['clarified butter']::text[],'animal',false,true,NULL,'Clarified butter from cow milk; vegetarian but not vegan.',NULL,0.95,'verified'),
('whey','Whey','{}'::text[],'animal',false,true,NULL,'Milk protein byproduct; vegetarian but not vegan.',NULL,0.95,'verified'),
('whey-protein','Whey Protein','{}'::text[],'animal',false,true,NULL,'Dairy protein; vegetarian but not vegan.',NULL,0.95,'verified'),
('whey-protein-concentrate','Whey Protein Concentrate',ARRAY['wpc']::text[],'animal',false,true,NULL,'Dairy protein; vegetarian but not vegan.',NULL,0.95,'verified'),
('caseinate','Caseinate',ARRAY['sodium caseinate','calcium caseinate']::text[],'animal',false,true,NULL,'Dairy protein salt; vegetarian but not vegan.',NULL,0.95,'verified'),
('milk-powder','Milk Powder',ARRAY['powdered milk','dry milk']::text[],'animal',false,true,NULL,'Dried milk; vegetarian but not vegan.',NULL,0.95,'verified'),
('condensed-milk','Condensed Milk',ARRAY['sweetened condensed milk']::text[],'animal',false,true,NULL,'Concentrated sweetened milk; vegetarian but not vegan.',NULL,0.95,'verified'),
('evaporated-milk','Evaporated Milk','{}'::text[],'animal',false,true,NULL,'Concentrated milk; vegetarian but not vegan.',NULL,0.95,'verified'),
('yogurt','Yogurt',ARRAY['yoghurt']::text[],'animal',false,true,NULL,'Fermented dairy; vegetarian but not vegan.',NULL,0.95,'verified'),
('kefir','Kefir','{}'::text[],'animal',false,true,NULL,'Fermented dairy drink; vegetarian but not vegan.',NULL,0.95,'verified'),
('sour-cream','Sour Cream','{}'::text[],'animal',false,true,NULL,'Fermented cream; vegetarian but not vegan.',NULL,0.95,'verified'),
('mascarpone','Mascarpone','{}'::text[],'animal',false,true,NULL,'Italian cream cheese; vegetarian but not vegan.',NULL,0.95,'verified'),
('ricotta','Ricotta','{}'::text[],'animal',false,true,NULL,'Whey cheese; vegetarian but not vegan.',NULL,0.95,'verified'),
('mozzarella','Mozzarella','{}'::text[],'animal',false,true,NULL,'Italian cheese; vegetarian but not vegan.',NULL,0.95,'verified'),
('cheddar','Cheddar','{}'::text[],'animal',false,true,NULL,'Cheese; vegetarian but not vegan (check rennet source).',NULL,0.9,'verified'),
('feta','Feta','{}'::text[],'animal',false,true,NULL,'Cheese; vegetarian but not vegan.',NULL,0.95,'verified'),
('brie','Brie','{}'::text[],'animal',false,true,NULL,'Soft cheese; vegetarian but not vegan.',NULL,0.95,'verified'),
('camembert','Camembert','{}'::text[],'animal',false,true,NULL,'Soft cheese; vegetarian but not vegan.',NULL,0.95,'verified'),
('blue-cheese','Blue Cheese',ARRAY['gorgonzola','roquefort']::text[],'animal',false,true,NULL,'Cheese; vegetarian but not vegan.',NULL,0.95,'verified'),
('cottage-cheese','Cottage Cheese','{}'::text[],'animal',false,true,NULL,'Fresh cheese; vegetarian but not vegan.',NULL,0.95,'verified'),
('custard','Custard','{}'::text[],'animal',false,true,NULL,'Milk-and-egg-based dessert; vegetarian but not vegan.',NULL,0.95,'verified'),
('ice-cream','Ice Cream','{}'::text[],'animal',false,true,NULL,'Frozen dairy dessert; vegetarian but not vegan.',NULL,0.95,'verified'),
('milk-fat','Milk Fat',ARRAY['butterfat','anhydrous milk fat']::text[],'animal',false,true,NULL,'Dairy fat; vegetarian but not vegan.',NULL,0.95,'verified'),
('milk-solids','Milk Solids','{}'::text[],'animal',false,true,NULL,'Dried dairy components; vegetarian but not vegan.',NULL,0.95,'verified'),
('parmesan','Parmesan',ARRAY['parmigiano reggiano']::text[],'unknown',NULL,NULL,NULL,'Traditional Parmigiano Reggiano uses animal rennet and is not vegetarian. Generic "parmesan cheese" often uses microbial rennet — check the label.',NULL,0.6,'verified'),
('meringue','Meringue','{}'::text[],'animal',false,true,NULL,'Whipped egg white dessert; vegetarian but not vegan.',NULL,0.95,'verified'),
('egg-albumen','Egg Albumen',ARRAY['albumen']::text[],'animal',false,true,NULL,'Egg white; vegetarian but not vegan.',NULL,0.95,'verified'),
('dried-egg','Dried Egg',ARRAY['egg powder','powdered egg']::text[],'animal',false,true,NULL,'Powdered egg; vegetarian but not vegan.',NULL,0.95,'verified'),
('egg-wash','Egg Wash','{}'::text[],'animal',false,true,NULL,'Beaten egg glaze; vegetarian but not vegan.',NULL,0.95,'verified'),
('mayonnaise','Mayonnaise',ARRAY['mayo']::text[],'animal',false,true,NULL,'Egg-based emulsion; vegetarian but not vegan (vegan versions exist).',NULL,0.9,'verified'),
('sardine','Sardine','{}'::text[],'animal',false,false,NULL,'Fish; not vegetarian or vegan.',NULL,0.95,'verified'),
('tuna','Tuna','{}'::text[],'animal',false,false,NULL,'Fish; not vegetarian or vegan.',NULL,0.95,'verified'),
('salmon','Salmon','{}'::text[],'animal',false,false,NULL,'Fish; not vegetarian or vegan.',NULL,0.95,'verified'),
('mackerel','Mackerel','{}'::text[],'animal',false,false,NULL,'Fish; not vegetarian or vegan.',NULL,0.95,'verified'),
('herring','Herring','{}'::text[],'animal',false,false,NULL,'Fish; not vegetarian or vegan.',NULL,0.95,'verified'),
('cod','Cod','{}'::text[],'animal',false,false,NULL,'Fish; not vegetarian or vegan.',NULL,0.95,'verified'),
('tilapia','Tilapia','{}'::text[],'animal',false,false,NULL,'Fish; not vegetarian or vegan.',NULL,0.95,'verified'),
('trout','Trout','{}'::text[],'animal',false,false,NULL,'Fish; not vegetarian or vegan.',NULL,0.95,'verified'),
('shrimp','Shrimp',ARRAY['prawn']::text[],'animal',false,false,NULL,'Crustacean; not vegetarian or vegan.',NULL,0.95,'verified'),
('scallop','Scallop','{}'::text[],'animal',false,false,NULL,'Mollusk; not vegetarian or vegan.',NULL,0.95,'verified'),
('oyster','Oyster','{}'::text[],'animal',false,false,NULL,'Mollusk; not vegetarian or vegan.',NULL,0.95,'verified'),
('mussel','Mussel','{}'::text[],'animal',false,false,NULL,'Mollusk; not vegetarian or vegan.',NULL,0.95,'verified'),
('octopus','Octopus','{}'::text[],'animal',false,false,NULL,'Cephalopod; not vegetarian or vegan.',NULL,0.95,'verified'),
('squid','Squid',ARRAY['calamari']::text[],'animal',false,false,NULL,'Cephalopod; not vegetarian or vegan.',NULL,0.95,'verified'),
('roe','Roe',ARRAY['fish eggs']::text[],'animal',false,false,NULL,'Fish eggs; not vegetarian or vegan.',NULL,0.95,'verified'),
('caviar','Caviar','{}'::text[],'animal',false,false,NULL,'Salted fish eggs; not vegetarian or vegan.',NULL,0.95,'verified'),
('worcestershire-sauce','Worcestershire Sauce','{}'::text[],'animal',false,false,NULL,'Contains anchovies; not vegetarian or vegan (vegan versions exist).',NULL,0.9,'verified'),
('fish-sauce','Fish Sauce',ARRAY['nam pla']::text[],'animal',false,false,NULL,'Fermented fish; not vegetarian or vegan.',NULL,0.95,'verified'),
('oyster-sauce','Oyster Sauce','{}'::text[],'animal',false,false,NULL,'Made from oysters; not vegetarian or vegan.',NULL,0.95,'verified'),
('shrimp-paste','Shrimp Paste','{}'::text[],'animal',false,false,NULL,'Fermented shrimp; not vegetarian or vegan.',NULL,0.95,'verified'),
('royal-jelly','Royal Jelly','{}'::text[],'animal',false,true,NULL,'Bee secretion; vegetarian but not vegan.',NULL,0.95,'verified'),
('propolis','Propolis','{}'::text[],'animal',false,true,NULL,'Bee resin; vegetarian but not vegan.',NULL,0.95,'verified'),
('mono-and-diglycerides','Mono- and Diglycerides',ARRAY['mono and diglycerides','monoglycerides','diglycerides']::text[],'unknown',NULL,NULL,NULL,'Mono- and diglycerides can be made from plant oils or animal fats. Manufacturer disclosure is needed to confirm vegan status.','E471',0.6,'verified'),
('glycerol','Glycerol',ARRAY['glycerine','glycerin']::text[],'unknown',NULL,NULL,NULL,'Glycerol can be plant-derived (soy, palm) or animal-derived (tallow). Source is rarely disclosed on labels.','E422',0.6,'verified'),
('stearic-acid','Stearic Acid','{}'::text[],'unknown',NULL,NULL,NULL,'Stearic acid can come from plants (cocoa butter, palm) or animal fat. Source is not typically listed.','E570',0.6,'verified'),
('palmitic-acid','Palmitic Acid','{}'::text[],'unknown',NULL,NULL,NULL,'Palmitic acid is usually plant-derived (palm) but can be animal-sourced.',NULL,0.6,'verified'),
('oleic-acid','Oleic Acid','{}'::text[],'unknown',NULL,NULL,NULL,'Oleic acid is generally from vegetable oils but can come from animal fat.',NULL,0.6,'verified'),
('sodium-stearoyl-lactylate','Sodium Stearoyl Lactylate',ARRAY['ssl']::text[],'unknown',NULL,NULL,NULL,'SSL is an emulsifier from stearic acid, which may be plant or animal-derived.','E481',0.6,'verified'),
('polyglycerol-esters','Polyglycerol Esters of Fatty Acids','{}'::text[],'unknown',NULL,NULL,NULL,'Made from glycerol and fatty acids that can be plant or animal in origin.','E475',0.6,'verified'),
('sorbitan-monostearate','Sorbitan Monostearate','{}'::text[],'unknown',NULL,NULL,NULL,'Emulsifier from stearic acid, which can be plant or animal-sourced.','E491',0.6,'verified'),
('polysorbate-60','Polysorbate 60','{}'::text[],'unknown',NULL,NULL,NULL,'Made with stearic acid; source can be plant or animal.','E435',0.6,'verified'),
('polysorbate-80','Polysorbate 80','{}'::text[],'unknown',NULL,NULL,NULL,'Made with oleic acid; source can be plant or animal.','E433',0.6,'verified'),
('polysorbate-20','Polysorbate 20','{}'::text[],'unknown',NULL,NULL,NULL,'Made with lauric acid; source is usually plant but can be animal-derived.','E432',0.6,'verified'),
('natural-flavor','Natural Flavor',ARRAY['natural flavors','natural flavour','natural flavours']::text[],'unknown',NULL,NULL,NULL,'Natural flavors may be plant, animal, or microbial in origin. The FDA/EU does not require the source to be disclosed.',NULL,0.6,'verified'),
('vitamin-d3','Vitamin D3',ARRAY['cholecalciferol']::text[],'unknown',NULL,NULL,NULL,'Vitamin D3 is usually extracted from lanolin (sheep wool) — not vegan. Plant-based D3 from lichen exists but must be specified.',NULL,0.6,'verified'),
('vitamin-d2','Vitamin D2',ARRAY['ergocalciferol']::text[],'plant',true,true,NULL,'Vitamin D2 is derived from yeast or fungi and is vegan-friendly.',NULL,0.95,'verified'),
('omega-3','Omega-3','{}'::text[],'unknown',NULL,NULL,NULL,'Omega-3 is commonly from fish oil but plant sources (algae, flax) exist. Source must be specified.',NULL,0.6,'verified'),
('dha','DHA',ARRAY['docosahexaenoic acid']::text[],'unknown',NULL,NULL,NULL,'DHA is typically from fish oil or algae. Only algal DHA is vegan.',NULL,0.6,'verified'),
('epa','EPA',ARRAY['eicosapentaenoic acid']::text[],'unknown',NULL,NULL,NULL,'EPA is typically from fish oil; algal versions exist but are less common.',NULL,0.6,'verified'),
('l-cystine','L-Cystine','{}'::text[],'unknown',NULL,NULL,NULL,'L-Cystine can be produced from human hair, duck feathers, or plant fermentation. Source is rarely disclosed.',NULL,0.6,'verified'),
('taurine','Taurine','{}'::text[],'unknown',NULL,NULL,NULL,'Taurine is now usually synthetic and vegan, but historically from animal bile. Check the manufacturer.',NULL,0.6,'verified'),
('glucosamine','Glucosamine','{}'::text[],'unknown',NULL,NULL,NULL,'Glucosamine is usually from shellfish; vegan versions from fungi (aspergillus) exist.',NULL,0.6,'verified'),
('squalene','Squalene','{}'::text[],'unknown',NULL,NULL,NULL,'Squalene may come from shark liver oil or plant sources (olive, amaranth).',NULL,0.6,'verified'),
('carotenes','Carotenes',ARRAY['mixed carotenes']::text[],'plant',true,true,NULL,'Carotenes are plant-derived pigments and vegan.','E160a',0.95,'verified'),
('chondroitin','Chondroitin',ARRAY['chondroitin sulfate']::text[],'animal',false,false,NULL,'Chondroitin sulfate is extracted from animal cartilage (cow, pig, or shark). Not vegetarian or vegan.',NULL,0.95,'verified'),
('tartrazine','Tartrazine',ARRAY['yellow 5']::text[],'synthetic',true,true,NULL,'Synthetic azo dye; vegan and vegetarian.','E102',0.95,'verified'),
('quinoline-yellow','Quinoline Yellow','{}'::text[],'synthetic',true,true,NULL,'Synthetic coal-tar dye; vegan and vegetarian.','E104',0.95,'verified'),
('sunset-yellow','Sunset Yellow FCF',ARRAY['yellow 6']::text[],'synthetic',true,true,NULL,'Synthetic azo dye; vegan and vegetarian.','E110',0.95,'verified'),
('ponceau-4r','Ponceau 4R','{}'::text[],'synthetic',true,true,NULL,'Synthetic azo dye; vegan and vegetarian.','E124',0.95,'verified'),
('patent-blue-v','Patent Blue V','{}'::text[],'synthetic',true,true,NULL,'Synthetic dye; vegan and vegetarian.','E131',0.95,'verified'),
('green-s','Green S','{}'::text[],'synthetic',true,true,NULL,'Synthetic dye; vegan and vegetarian.','E142',0.95,'verified'),
('titanium-dioxide','Titanium Dioxide','{}'::text[],'mineral',true,true,NULL,'Mineral whitening pigment; vegan and vegetarian.','E171',0.95,'verified'),
('calcium-hydroxide','Calcium Hydroxide',ARRAY['slaked lime']::text[],'mineral',true,true,NULL,'Mineral acidity regulator; vegan and vegetarian.','E526',0.95,'verified'),
('sodium-hydroxide','Sodium Hydroxide',ARRAY['lye']::text[],'mineral',true,true,NULL,'Mineral acidity regulator; vegan and vegetarian.','E524',0.95,'verified'),
('potassium-hydroxide','Potassium Hydroxide','{}'::text[],'mineral',true,true,NULL,'Mineral acidity regulator; vegan and vegetarian.','E525',0.95,'verified'),
('ammonium-hydroxide','Ammonium Hydroxide','{}'::text[],'mineral',true,true,NULL,'Synthetic acidity regulator; vegan and vegetarian.','E527',0.95,'verified'),
('tricalcium-phosphate','Tricalcium Phosphate','{}'::text[],'mineral',true,true,NULL,'Mineral anti-caking agent; vegan and vegetarian.','E341',0.95,'verified'),
('disodium-phosphate','Disodium Phosphate','{}'::text[],'mineral',true,true,NULL,'Mineral emulsifier salt; vegan and vegetarian.','E339',0.95,'verified'),
('potassium-sorbate','Potassium Sorbate','{}'::text[],'synthetic',true,true,NULL,'Synthetic preservative; vegan and vegetarian.','E202',0.95,'verified'),
('sodium-benzoate','Sodium Benzoate','{}'::text[],'synthetic',true,true,NULL,'Synthetic preservative; vegan and vegetarian.','E211',0.95,'verified'),
('sulfur-dioxide','Sulfur Dioxide','{}'::text[],'synthetic',true,true,NULL,'Preservative and antioxidant; vegan and vegetarian.','E220',0.95,'verified'),
('sodium-sulfite','Sodium Sulfite','{}'::text[],'synthetic',true,true,NULL,'Preservative; vegan and vegetarian.','E221',0.95,'verified'),
('sodium-nitrite','Sodium Nitrite','{}'::text[],'synthetic',true,true,NULL,'Curing agent used in meat; the compound itself is vegan.','E250',0.95,'verified'),
('sodium-nitrate','Sodium Nitrate','{}'::text[],'synthetic',true,true,NULL,'Curing agent; the compound itself is vegan.','E251',0.95,'verified'),
('potassium-nitrate','Potassium Nitrate',ARRAY['saltpeter']::text[],'synthetic',true,true,NULL,'Curing agent; the compound itself is vegan.','E252',0.95,'verified'),
('propionic-acid','Propionic Acid','{}'::text[],'synthetic',true,true,NULL,'Preservative; vegan and vegetarian.','E280',0.95,'verified'),
('calcium-propionate','Calcium Propionate','{}'::text[],'synthetic',true,true,NULL,'Bread preservative; vegan and vegetarian.','E282',0.95,'verified'),
('sodium-propionate','Sodium Propionate','{}'::text[],'synthetic',true,true,NULL,'Preservative; vegan and vegetarian.','E281',0.95,'verified'),
('natamycin','Natamycin','{}'::text[],'microbial',true,true,NULL,'Antifungal produced by bacterial fermentation; vegan.','E235',0.95,'verified'),
('nisin','Nisin','{}'::text[],'microbial',true,true,NULL,'Antibacterial from lactic acid bacteria; vegan.','E234',0.95,'verified'),
('invertase','Invertase','{}'::text[],'microbial',true,true,NULL,'Enzyme from yeast; vegan.','E1103',0.95,'verified'),
('propylene-glycol','Propylene Glycol','{}'::text[],'synthetic',true,true,NULL,'Synthetic humectant; vegan and vegetarian.','E1520',0.95,'verified'),
('dimethylpolysiloxane','Dimethylpolysiloxane',ARRAY['pdms']::text[],'synthetic',true,true,NULL,'Synthetic anti-foaming agent; vegan.','E900',0.95,'verified'),
('polyethylene-glycol','Polyethylene Glycol',ARRAY['peg']::text[],'synthetic',true,true,NULL,'Synthetic; vegan and vegetarian.','E1521',0.95,'verified'),
('silicon-dioxide','Silicon Dioxide',ARRAY['silica']::text[],'mineral',true,true,NULL,'Mineral anti-caking agent; vegan and vegetarian.','E551',0.95,'verified'),
('potassium-chloride','Potassium Chloride','{}'::text[],'mineral',true,true,NULL,'Mineral salt substitute; vegan and vegetarian.','E508',0.95,'verified'),
('sodium-bicarbonate','Sodium Bicarbonate',ARRAY['baking soda']::text[],'mineral',true,true,NULL,'Mineral leavening; vegan and vegetarian.','E500',0.95,'verified'),
('potassium-bicarbonate','Potassium Bicarbonate','{}'::text[],'mineral',true,true,NULL,'Mineral leavening; vegan and vegetarian.','E501',0.95,'verified'),
('monopotassium-phosphate','Monopotassium Phosphate','{}'::text[],'mineral',true,true,NULL,'Mineral acidity regulator; vegan and vegetarian.','E340',0.95,'verified'),
('sodium-aluminium-phosphate','Sodium Aluminium Phosphate','{}'::text[],'mineral',true,true,NULL,'Mineral leavening; vegan and vegetarian.','E541',0.95,'verified'),
('tartaric-acid','Tartaric Acid','{}'::text[],'plant',true,true,NULL,'Plant-derived acid (grapes); vegan and vegetarian.','E334',0.95,'verified'),
('sodium-tartrate','Sodium Tartrate','{}'::text[],'plant',true,true,NULL,'From tartaric acid; vegan and vegetarian.','E335',0.95,'verified'),
('potassium-tartrate','Potassium Tartrate','{}'::text[],'plant',true,true,NULL,'From tartaric acid; vegan and vegetarian.','E336',0.95,'verified'),
('fumaric-acid','Fumaric Acid','{}'::text[],'synthetic',true,true,NULL,'Synthetic acidulant; vegan and vegetarian.','E297',0.95,'verified'),
('succinic-acid','Succinic Acid','{}'::text[],'synthetic',true,true,NULL,'Acidulant; vegan and vegetarian.','E363',0.95,'verified'),
('adipic-acid','Adipic Acid','{}'::text[],'synthetic',true,true,NULL,'Acidulant; vegan and vegetarian.','E355',0.95,'verified'),
('sodium-citrate','Sodium Citrate','{}'::text[],'synthetic',true,true,NULL,'Buffer salt; vegan and vegetarian.','E331',0.95,'verified'),
('potassium-citrate','Potassium Citrate','{}'::text[],'synthetic',true,true,NULL,'Buffer salt; vegan and vegetarian.','E332',0.95,'verified'),
('calcium-lactate','Calcium Lactate','{}'::text[],'synthetic',true,true,NULL,'Calcium salt of lactic acid; vegan and vegetarian.','E327',0.95,'verified'),
('sodium-lactate','Sodium Lactate','{}'::text[],'synthetic',true,true,NULL,'Sodium salt of lactic acid; vegan and vegetarian.','E325',0.95,'verified'),
('xanthan-gum','Xanthan Gum','{}'::text[],'microbial',true,true,NULL,'Made by bacterial fermentation; vegan and vegetarian.','E415',0.95,'verified'),
('gellan-gum','Gellan Gum','{}'::text[],'microbial',true,true,NULL,'Made by bacterial fermentation; vegan and vegetarian.','E418',0.95,'verified'),
('konjac','Konjac',ARRAY['konjac gum','glucomannan']::text[],'plant',true,true,NULL,'From konjac plant; vegan and vegetarian.','E425',0.95,'verified'),
('pectin','Pectin','{}'::text[],'plant',true,true,NULL,'From fruit peels; vegan and vegetarian.','E440',0.95,'verified'),
('modified-starch','Modified Starch','{}'::text[],'plant',true,true,NULL,'Starch chemically modified; vegan and vegetarian.','E1400',0.95,'verified'),
('dextrin','Dextrin','{}'::text[],'plant',true,true,NULL,'From starch; vegan and vegetarian.',NULL,0.95,'verified'),
('inositol','Inositol','{}'::text[],'plant',true,true,NULL,'Naturally in plants; vegan and vegetarian.',NULL,0.95,'verified'),
('choline','Choline',ARRAY['choline bitartrate']::text[],'synthetic',true,true,NULL,'Usually synthetic; vegan and vegetarian.',NULL,0.95,'verified'),
('niacinamide','Niacinamide',ARRAY['nicotinamide','vitamin b3']::text[],'synthetic',true,true,NULL,'Synthetic B3; vegan and vegetarian.',NULL,0.95,'verified'),
('riboflavin','Riboflavin',ARRAY['vitamin b2']::text[],'microbial',true,true,NULL,'Now made by fermentation; vegan and vegetarian.','E101',0.95,'verified'),
('folic-acid','Folic Acid',ARRAY['vitamin b9']::text[],'synthetic',true,true,NULL,'Synthetic B vitamin; vegan and vegetarian.',NULL,0.95,'verified'),
('thiamine','Thiamine',ARRAY['vitamin b1','thiamine mononitrate']::text[],'synthetic',true,true,NULL,'Synthetic B1; vegan and vegetarian.',NULL,0.95,'verified'),
('cyanocobalamin','Cyanocobalamin',ARRAY['vitamin b12']::text[],'microbial',true,true,NULL,'Made by bacterial fermentation; vegan and vegetarian.',NULL,0.95,'verified'),
('pyridoxine','Pyridoxine',ARRAY['vitamin b6']::text[],'synthetic',true,true,NULL,'Synthetic B6; vegan and vegetarian.',NULL,0.95,'verified'),
('biotin','Biotin',ARRAY['vitamin b7']::text[],'synthetic',true,true,NULL,'Usually synthetic or fermentation-derived; vegan.',NULL,0.95,'verified'),
('pantothenic-acid','Pantothenic Acid',ARRAY['vitamin b5']::text[],'synthetic',true,true,NULL,'Synthetic B5; vegan and vegetarian.',NULL,0.95,'verified'),
('vitamin-a-palmitate','Vitamin A Palmitate',ARRAY['retinyl palmitate']::text[],'synthetic',true,true,NULL,'Usually synthetic; vegan.',NULL,0.95,'verified'),
('vitamin-e','Vitamin E',ARRAY['tocopherol','tocopherols']::text[],'plant',true,true,NULL,'Usually from vegetable oils; vegan and vegetarian.','E307',0.95,'verified'),
('vitamin-k','Vitamin K',ARRAY['phytonadione','phylloquinone']::text[],'synthetic',true,true,NULL,'Synthetic or plant-derived; vegan.',NULL,0.95,'verified'),
('zinc-oxide','Zinc Oxide','{}'::text[],'mineral',true,true,NULL,'Mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('zinc-sulfate','Zinc Sulfate','{}'::text[],'mineral',true,true,NULL,'Mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('ferrous-sulfate','Ferrous Sulfate','{}'::text[],'mineral',true,true,NULL,'Iron mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('ferrous-fumarate','Ferrous Fumarate','{}'::text[],'mineral',true,true,NULL,'Iron supplement; vegan and vegetarian.',NULL,0.95,'verified'),
('magnesium-oxide','Magnesium Oxide','{}'::text[],'mineral',true,true,NULL,'Mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('copper-sulfate','Copper Sulfate','{}'::text[],'mineral',true,true,NULL,'Mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('selenium','Selenium',ARRAY['sodium selenite']::text[],'mineral',true,true,NULL,'Mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('iodine','Iodine',ARRAY['potassium iodide']::text[],'mineral',true,true,NULL,'Mineral; vegan and vegetarian.',NULL,0.95,'verified'),
('vegan-cheese','Vegan Cheese',ARRAY['plant-based cheese']::text[],'plant',true,true,NULL,'Plant-based cheese; vegan and vegetarian.',NULL,0.95,'verified'),
('vegan-butter','Vegan Butter',ARRAY['plant butter']::text[],'plant',true,true,NULL,'Plant-based butter; vegan and vegetarian.',NULL,0.95,'verified'),
('coconut-yogurt','Coconut Yogurt','{}'::text[],'plant',true,true,NULL,'Plant-based yogurt; vegan and vegetarian.',NULL,0.95,'verified'),
('almond-yogurt','Almond Yogurt','{}'::text[],'plant',true,true,NULL,'Plant-based yogurt; vegan and vegetarian.',NULL,0.95,'verified'),
('soy-yogurt','Soy Yogurt','{}'::text[],'plant',true,true,NULL,'Plant-based yogurt; vegan and vegetarian.',NULL,0.95,'verified'),
('aquafaba','Aquafaba',ARRAY['chickpea water']::text[],'plant',true,true,NULL,'Chickpea cooking liquid; vegan and vegetarian.',NULL,0.95,'verified')
ON CONFLICT (slug) DO NOTHING;